name: Run new-release script

on:
  repository_dispatch:
    types: [publish]

jobs:
  generate_diffs:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup asdf
        uses: asdf-vm/actions/setup@6844d09b13209e7d2ce3b63d2b089a2acef581ec

      - name: Cache asdf
        uses: actions/cache@v3
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ '**/.tool-versions' }}
          restore-keys: |
            ${{ runner.os }}-asdf-

      - name: asdf install
        uses: asdf-vm/actions/install@6844d09b13209e7d2ce3b63d2b089a2acef581ec

      - name: yarn install
        run: yarn install

      - name: Run new-release script
        run: ./new-release.sh ${{ github.event.client_payload.version }}
